sudo: required

language: php

services:
  - docker

env:
  - SYMFONY_ENV=dev

script: php bin/console about


script:
  - docker-compose build
  - docker-compose run --rm web bin/console security:check
  - docker-compose run --rm web bin/console php bin/console about
