sudo: required

services:
  - docker

env:
  - SYMFONY_ENV=dev

script: php bin/console about


script:
  - docker-compose build
  - docker-compose run --rm app bin/console security:check
  - docker-compose run --rm app bin/console php bin/console about
