<?php

namespace AppBundle\Repository;

/**
 * ArticleStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
