<?php

namespace AppBundle\Repository;

/**
 * ArticleVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
