<?php

namespace AppBundle\Repository;

/**
 * SuggestionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
