<?php

namespace AppBundle\Repository;

/**
 * SuggestionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
