parameters:

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    query_service:
      class: AppBundle\Services\QueryService
      arguments: ["@service_container"]
